all:
  children:
    manager:
      hosts:
        3.87.206.235:
    worker:
      hosts:
        54.167.139.56:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: "/usr/bin/python3"
